const fs = require('fs');
let c = fs.readFileSync('src/components/pos/HistorialVentas.tsx', 'utf-8');
c = c.replace(/{\\` /g, '{` ');
c = c.replace(/{\\`transition/g, '{`transition');
c = c.replace(/\\`}/g, '`}');
c = c.replace(/\\\${/g, '${');
c = c.replace(/key={\\`pad/g, 'key={`pad');
c = c.replace(/className={\\`relative/g, 'className={`relative');
fs.writeFileSync('src/components/pos/HistorialVentas.tsx', c);
console.log('Fixed');
