const fs = require('fs');
let code = fs.readFileSync('src/app/dashboard/compras/page.tsx', 'utf8');

const stateSearch = "  const [alertMsg, setAlertMsg] = useState({ text: '', type: '' });";
const stateReplace = stateSearch + "\n\n  // --- ESTADO MODAL PROMPT ---\n  const [promptModal, setPromptModal] = useState({\n    isOpen: false,\n    title: '',\n    placeholder: '',\n    value: '',\n    onSubmit: (val: string) => {}\n  });\n\n  const openPrompt = (title: string, placeholder: string, onSubmit: (val: string) => void) => {\n    setPromptModal({ isOpen: true, title, placeholder, value: '', onSubmit });\n  };\n  \n  const closePrompt = () => {\n    setPromptModal(prev => ({...prev, isOpen: false}));\n  };";

code = code.replace(stateSearch, stateReplace);

const oldProdChange = "  const handleProductoChange = (rowId: number, field: string, value: string) => {\n    if (field === 'id_producto' && value === 'NEW_PRODUCT') {\n      const nombre = prompt('Ingresa el nombre del nuevo producto base:');\n      if (nombre && nombre.trim()) {\n        setIsSubmitting(true);\n        crearProductoBase(nombre.trim()).then(res => {\n          if (res.success) {\n            setProductosDb(prev => [...prev, res.producto!]);\n            mostrarAlerta('Producto creado.', 'success');\n            setProductos(prev => prev.map(p => {\n              if (p.rowId === rowId) {\n                return { ...p, id_producto: res.producto!.id, precio: '0', total: '0' };\n              }\n              return p;\n            }));\n          } else {\n            mostrarAlerta(res.error, 'error');\n          }\n          setIsSubmitting(false);\n        });\n      }\n      return;\n    }";
const newProdChange = "  const handleProductoChange = (rowId: number, field: string, value: string) => {\n    if (field === 'id_producto' && value === 'NEW_PRODUCT') {\n      openPrompt('Crear Nuevo Producto Base', 'Ej: Cemento Gris', (nombre) => {\n        if (nombre && nombre.trim()) {\n          setIsSubmitting(true);\n          crearProductoBase(nombre.trim()).then(res => {\n            if (res.success) {\n              setProductosDb(prev => [...prev, res.producto!]);\n              mostrarAlerta('Producto creado.', 'success');\n              setProductos(prev => prev.map(p => {\n                if (p.rowId === rowId) {\n                  return { ...p, id_producto: res.producto!.id, precio: '0', total: '0' };\n                }\n                return p;\n              }));\n            } else {\n              mostrarAlerta(res.error, 'error');\n            }\n            setIsSubmitting(false);\n          });\n        } else {\n          setProductos(prev => prev.map(p => p.rowId === rowId ? { ...p, id_producto: '' } : p));\n        }\n      });\n      return;\n    }";

code = code.replace(oldProdChange, newProdChange);

const provSearchCorrupt = /const handleCrearProveedorRapido = async \(\) => {[\s\S]*?setIsSubmitting\(false\);\n      }\n    };/;
const provReplaceFinal = "const handleCrearProveedorRapido = () => {\n    openPrompt('Crear Nuevo Proveedor', 'Ej: Inversiones ABC - J-1234567', async (nombre) => {\n      if (nombre && nombre.trim()) {\n        setIsSubmitting(true);\n        const res = await crearProveedor(nombre.trim());\n        if (res.success) {\n          setProveedoresDb(prev => [...prev, res.proveedor]);\n          setFactura(prev => ({...prev, proveedor: res.proveedor?.id?.toString() || ''}));\n          mostrarAlerta('Proveedor creado.', 'success');\n        }\n        setIsSubmitting(false);\n      }\n    });\n  };";

code = code.replace(provSearchCorrupt, provReplaceFinal);

const uiSearch = "{/* ALERTA FLOTANTE */}";
const uiReplace = "{/* PROMPT MODAL PROPIO */}\n      {promptModal.isOpen && (\n        <div className=\"fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-in fade-in\">\n          <div className=\"bg-neutral-900 border border-neutral-800 rounded-2xl w-full max-w-md shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200\">\n            <div className=\"flex justify-between items-center p-6 border-b border-neutral-800 bg-neutral-900/50\">\n              <h3 className=\"text-lg font-medium text-white\">{promptModal.title}</h3>\n              <button onClick={closePrompt} className=\"text-neutral-500 hover:text-white transition-colors\">\n                <X size={20} />\n              </button>\n            </div>\n            <div className=\"p-6\">\n              <input \n                type=\"text\" \n                autoFocus\n                value={promptModal.value} \n                onChange={e => setPromptModal(prev => ({...prev, value: e.target.value}))} \n                onKeyDown={e => {\n                  if(e.key === 'Enter') {\n                    closePrompt();\n                    promptModal.onSubmit(promptModal.value);\n                  }\n                }}\n                placeholder={promptModal.placeholder} \n                className=\"w-full bg-black/50 border border-neutral-800 text-white rounded-xl px-4 py-3 focus:outline-none focus:ring-1 focus:ring-indigo-500\" \n              />\n              <div className=\"flex gap-3 mt-8\">\n                <button onClick={closePrompt} className=\"flex-1 bg-neutral-800 hover:bg-neutral-700 text-white font-medium py-2.5 rounded-xl transition-colors\">\n                  Cancelar\n                </button>\n                <button onClick={() => { closePrompt(); promptModal.onSubmit(promptModal.value); }} className=\"flex-1 bg-indigo-600 hover:bg-indigo-500 text-white font-medium py-2.5 rounded-xl transition-colors\">\n                  Aceptar\n                </button>\n              </div>\n            </div>\n          </div>\n        </div>\n      )}\n\n      {/* ALERTA FLOTANTE */}";

code = code.replace(uiSearch, uiReplace);

fs.writeFileSync('src/app/dashboard/compras/page.tsx', code, 'utf8');
